# -*- coding: utf-8 -*-
"""Vendas - Identificar Anomalias em vendas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1me1aOX40ty-_rJ5fbeR8BexXoWIStDz8
"""

import pandas as pd
import numpy as np
from io import StringIO
from sklearn.ensemble import IsolationForest

# 1. Criar dados de vendas normais (Tendência + Ruído)
np.random.seed(42)
dias = pd.date_range(start="2024-10-01", periods=30, freq='D')
vendas_base = np.linspace(500, 600, 30) + np.random.normal(0, 20, 30)
df_vendas = pd.DataFrame({'Data': dias, 'Vendas_R': vendas_base.round(2)})

# 2. Inserir Anomalias:

# Anomalia A: Aumento repentino e inesperado (Dia 10)
df_vendas.loc[df_vendas['Data'] == '2024-10-10', 'Vendas_R'] = 1200.00

# Anomalia B: Redução drástica sem razão (Dia 25)
df_vendas.loc[df_vendas['Data'] == '2024-10-25', 'Vendas_R'] = 50.00

# 3. Adicionar uma Feature de Contexto (ex: Tráfego do Site)
df_vendas['Trafego_Site'] = (df_vendas['Vendas_R'] / 2) + np.random.normal(0, 10, 30)
df_vendas['Trafego_Site'] = df_vendas['Trafego_Site'].round(0)

# 4. Definir Features (X) para detecção de anomalias
# Usaremos 'Vendas_R' e 'Trafego_Site' para detecção multidimensional
X = df_vendas[['Vendas_R', 'Trafego_Site']]

print("--- Dados de Vendas Simulados (30 Dias) ---")
print(df_vendas.head(12))

# Instanciar e Treinar o Isolation Forest
# contamination: estimativa da proporção de outliers no dataset (aqui 5%)
model_anomalia = IsolationForest(contamination=0.05, random_state=42)

# O Isolation Forest é um modelo não supervisionado, treina-se apenas com X
model_anomalia.fit(X)

print("\n--- Treinamento do Isolation Forest Concluído! ---")

# 1. Prever anomalias
# O modelo retorna 1 (Normal) ou -1 (Anomalia)
df_vendas['Anomalia'] = model_anomalia.predict(X)

# 2. Obter a pontuação de Anomalia (quanto mais negativo, mais anômalo)
df_vendas['Score_Anomalia'] = model_anomalia.decision_function(X)

# Filtrar apenas as Anomalias
anomalias_detectadas = df_vendas[df_vendas['Anomalia'] == -1].sort_values(by='Score_Anomalia')

print("\n--- Anomalias Detectadas (Ordenadas por Risco) ---")
print(anomalias_detectadas)

# Interpretação dos Resultados
print("\n--- Interpretação e Ação Preventiva ---")

for index, row in anomalias_detectadas.iterrows():
    data = row['Data'].strftime('%Y-%m-%d')
    vendas = row['Vendas_R']
    trafego = row['Trafego_Site']

    if vendas > 1000 and trafego < 600:
        print(f"Data: {data} -> ALERTA MÁXIMO (PICO DE VENDA INESPERADO: R$ {vendas:.2f}). Tráfego não justifica o volume. **Investigar Fraude/Bug**.")
    elif vendas < 100 and trafego < 50:
        print(f"Data: {data} -> ALERTA CRÍTICO (QUEDA DRÁSTICA: R$ {vendas:.2f}). **Investigar Falha de Estoque/Sistema de Pagamento**.")
    else:
        print(f"Data: {data} -> Anomalia Leve. Vendas: R$ {vendas:.2f}. Score: {row['Score_Anomalia']:.2f}")